### PR TITLE
add swagger editor docker compose file

### PR DESCRIPTION
**Pull request by PierreBesson**

### CODE REVIEW

**Comment by cbornet** [comment]
That's a good idea !
I've opened a PR to include the module in the main gen. Let's see if it gets approved :smile:

**Comment by PierreBesson** [comment]
And I see that you've added the "detoeuf" gradle plugin like I wanted to suggest !

**Comment by cbornet** [comment]
Yes. If the PR is not merged in the main gen, I'll port it to the module.

**Comment by cbornet** [comment]
The module is now part of the main gen.
So you can add the dockerized swagger-editor there !

**Pull request merged**
